volumes:
  pg_data:
    driver: local

x-base: &base-backend
  env_file:
    - .env
  environment:
    DATABASE_URL: postgres://db_user:db_password@db:5432/db_name
    DEBUG: "on"
    ENVIRONMENT: development
    ALLOWED_HOSTS: localhost,0.0.0.0
  volumes:
    - .:/code:delegated
  depends_on:
    - db

services:
  db:
    image: library/postgres:13
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # ports:
    #   - "5432:5432"


  backend:
    <<: *base-backend
    build: .
    command: sh -c "pip install django-allauth google-api-python-client google-auth-oauthlib cryptography && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"


